name: QuickBoard
author: Tejdik, Carson
version: 1.3-SNAPSHOT
main: me.tade.quickboard.QuickBoard
softdepend: [PlaceholderAPI, MVdWPlaceholders]
commands:
   quickboard:
      aliases: [qb, board, quickb, qbr, gbd]